
version: 2.1
  
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    environment:
      CC_TEST_REPORTER_ID: 3b3a7151bbc69bdf7ef9808abb4bf8cb69959782eec430f4d9ba650c6d84cff4 

    docker:
      - image: cimg/python:3.8.9
        environment:
          STATE: Testing
          DATABASE_TEST: postgresql://user@localhost/circleci_test?sslmode=disable
          SECRET_KEY: test-this-stackoverflow-api

      - image: cimg/postgres:14.2
        
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: circleci_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Setup Code Climate test-reporter
          command: |
          # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: pytest --cov=api --cov-report term-missing

workflows:
  sample: 
    jobs:
      - build-and-test