
version: 2.1
  
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:

    docker:
      - image: cimg/python:3.8.9
        environment:
          STATE: Testing
          DATABASE_TEST: postgresql://user@localhost/circleci_test?sslmode=disable
          SECRET_KEY: test-this-stackoverflow-api

      - image: cimg/postgres:14.2
        
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: circleci_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - script: |
          pip install coveralls
          export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
          coveralls
        displayName: 'coveralls'
        env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token) 

workflows:
  sample: 
    jobs:
      - build-and-test