
version: 2.1
  
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 

    docker:
      - image: cimg/python:3.8.9
        environment:
          STATE: Testing
          DATABASE_TEST: postgresql://user@localhost/circleci_test?sslmode=disable
          SECRET_KEY: test-this-stackoverflow-api

      - image: cimg/postgres:14.2
        
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: circleci_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest --cov=api --cov-report term-missing
      - run: 
          name: Upload coverage data to coveralls.io
          command: coveralls

workflows:
  sample: 
    jobs:
      - build-and-test